<!DOCTYPE html>
<html lang="en">

<head>
  <?php include "include/in_head.php"?>
</head>

<body class="skin-2">
  <?php include "include/in_navbar.php"?>
  <div class="main-container ace-save-state" id="main-container">
    <?php include "include/in_sidebar.php"?>
    <div class="main-content">
      <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state breadcrumbs-fixed" id="breadcrumbs">
          <ul class="breadcrumb">
            <li>
              <i class="ace-icon fa fa-home home-icon"></i>
              <a href="Char_index.php">首页</a>
            </li>
            <li>
              <a href="javascript:void(0)">会员需知设置</a>
            </li>
            <li>
              <a href="member_method.php">会员需知设置</a>
            </li>
          </ul><!-- /.breadcrumb -->
        </div>
        <div class="page-content">
          <?php include "include/in_menu_set.php"?>
          <div class="row">
            <div class="col-xs-12">
              <!-- 主要内容 开始 -->
              <form class="form-horizontal newoil-form" method="post"
                action="#">
                <div class="row">
                  <div class="col-xs-12 col-sm-12">
                    <div class="widget-box widget-color-blue2">
                      <div class="widget-header">
                        <h4 class="widget-title lighter smaller">会员需知设置</h4>
                      </div>
                      <div class="widget-body">
                        <div class="widget-main padding-8">
                          <div class="form-group">
                            <div class="col-xs-12 col-sm-12">
                              <textarea class="ckeditor" name="word">&lt;p&gt;&lt;span style=&quot;font-size:18px;&quot;&gt;待業主提供文案，以下為範例&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;歡迎您加入「666娛樂城」會員並使用「666娛樂城」所提供之各項會員服務。為保障您的權益，請詳細閱讀本服使用者合約所有內容，尤其當您在勾選「我已閱讀並同意使用者合約」，並註冊完成或開始使用本服務時，即視為您已經詳細閱讀、了解本使用者合約，並同意遵守以下使用者合約之約定。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第一條】 遵守會員規範及法律規定&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;您了解您註冊成為會員後，即可使用「666娛樂城」所提供之各項服務(以下稱本服務)。當會員使用本服務時，即表示除了同意遵守本服務條款外，還同意接受「666娛樂城」對「666娛樂城」會員規範（包括遊戲規則、公告及注意事項等）及相關法令規定之拘束。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第二條】 服務簡介&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（一）本平台為遊戲點數交易平台，僅提供遊戲點數交易；會員如因遊戲產生點數輸贏或任何不法情事，純屬會員個人之行為，與本平台無關。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（二）接受本服務之會員必須自行配備上網所需之各項電腦設備，並負擔包括但不限「網際網路連線費用」、「電話費用」等之電信相關費用。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（三）當您完成註冊程序後，即擁有之「666娛樂城」會員資格，並且可以開始使用本服務。您瞭解當您成為「666娛樂城」會員後而得使用之各&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;項會員服務，其所有權仍屬「666娛樂城」及其所約定之人所有，會員僅得依本服務條款之約定使用，不得出租、出借、移轉或讓與給其他第&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;三人使用。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（四）「666娛樂城」有權增加、變更或取消本服務中相關系統或功能之全部或一部份之權利，且無需個別通知會員；且有關現有或將來之各項服務&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;均受本服務條款之規範。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（五）虛擬貨幣服務：「666娛樂城」提供網路金流付費平台，你所購買的「666娛樂城」點數將可享受符合「666娛樂城」平台的服務。若您&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;使用不正當的方式進行儲值，「666娛樂城」也將保留隨時終止您會員資格及使用各項服務之權利。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第三條】 真實登錄義務&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;基於「666娛樂城」所提供之各項服務，您必須年滿 18 歲並同意於註冊時登錄您本人正確、真實及完整之個人資料；當您的個人資料有異動時，請立即更新，以維持您個人資料之正確、真實及完整。如因您登錄不實資料或冒用他人名義以致於侵害他人之權利或違法時，應自負法律責任。您同意您所提供之個人資料不實或個人資料有異動但沒有更新以致於與原登錄之資料不符時，「666娛樂城」有權隨時終止您的會員資格及使用各項會員服務之權利。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第四條】 會員規範之增訂及修改&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;本服務條款如有增訂或修改，您同意自該修訂條款於本網站公告之時起受其拘束，本網站將不對會員個別通知。如您於公告後繼續使用本服務，則視為您已經同意該修訂條款。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第五條】 服務之停止與更改&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（一）會員登錄之資料不實。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（二）未滿 18 歲者。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（三）使用中文、英文及數字以外之字元及不雅文字作為本服務之名稱。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（四）使用他人的名義&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（五）違反遊戲公平原則。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（六）參與遊戲或比賽時，故意鑽研系統漏洞或利用遊戲弱點以影響結果。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（七）違反本服務條款時。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;如有發現上述問題之玩家，「666娛樂城」有終止玩家帳號使用之權力；如有獲獎資格經核對證件發生上述問題，則取消獲獎資格。如有任何爭議問題，「666娛樂城」有最終決定權。無論任何情形，停止、更改服務或終止會員帳戶服務所可能產生之困擾、不便或損害，本服務對任何會員或第三人均不負任何責任。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第六條】 服務暫停或中斷&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（一）「666娛樂城」於下列情形之一時，得暫停或中斷本服務之全部或一部，對於使用者不負擔任何賠償責任：&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;1. 對於本服務相關系統設備進行遷移、更換或維護時。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;2. 因不可歸責於「666娛樂城」所造成服務停止或中斷。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;3. 因不可抗力所造成服務停止或中斷。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（二）如因「666娛樂城」對於本網站相關系統設備進行遷移、更換或維護而必須暫停或中斷全部或一部之服務時，「666娛樂城」於暫停或中斷&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;前將以電子郵件通知或於本網站上公告。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（三）因使用者違反法令或本服務條款或因不可歸責於「666娛樂城」之事由而造成本服務之全部或一部暫停或中斷時，暫停或中斷期間之費用仍&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;依正常標準計費。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（四）對於本服務之暫停或中斷，可能造成您使用上的不便、資料遺失或其他經濟及時間上之損失，您平時應採取適當的防護措施，以保障您的&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;權益。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第七條】 會員義務與責任&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（一）除了遵守本服務條款之約定外，您同意遵守「666娛樂城」之各項服務營業規章及網際網路國際使用慣例與禮節之相關規定，並同意不從事&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;以下行為；若被判定有以下行為時，「666娛樂城」將有權不另通知，自行刪除留言內容。違反規定者，我們將視情況予以處份，嚴重者，&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;其帳號可能會被停權：&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;1. 意圖破壞、入侵「666娛樂城」伺服器及官方網站；或有使用外掛程式、利用程式漏洞修改遊戲、侵入會員資料庫、散播電腦病毒程式及&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;竊取、更改、破壞「666娛樂城」或他人資訊情事等之行為者。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;2. 以「666娛樂城」或類似「666娛樂城」之名義使用本服務者。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;3. 使用本服務被判定有有犯罪行為或有相關嫌疑者。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;4. 侵害他人智慧財產權或其他權利或有侵害之虞者。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;5. 有故意妨礙「666娛樂城」的服務運作之行為者。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;6. 利用申告功能對其他玩家隨意誣告或使用本服務有損害他人名譽或侵害他人權利之行為者。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;7. 其他有危害通信或違反法令之情事或之虞者。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（二）上述規定不代表「666娛樂城」隨時會對會員做任何形式或實質之審查，會員必須對自己所做之行為負責。如經「666娛樂城」察覺或經他&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;人申訴會員有違反上述各款之情事或之虞時，「666娛樂城」除有權逕行移除或刪除該內容外，並有權終止或暫停該會員之會員資格及各項會&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;員服務。「666娛樂城」如因此產生損害或損失，並得向該會員請求賠償。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（三）會員同意妥善保管個人之帳號及密碼，並不得與他人共用；會員並應不定期更新自己密碼，並於使用完服務後確實將帳號作登出動作，以&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;免帳號被他人惡意盜用。 &lt;/span&gt;&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-family: Arial; font-size: 13.3333px; white-space: pre-wrap;&quot;&gt;（四）&lt;/span&gt;為了避免為3方詐騙，直接儲值會員，均需洗碼2倍以上，方可申請提領。 &amp;nbsp;&lt;br /&gt;
&amp;nbsp;( 五 ) 第一次提領會員，還請提供證件(身分證字號及換發時間地點)及帳戶封面做實名認證。&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第八條】 責任限制&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（一）「666娛樂城」之各項會員服務，依「666娛樂城」既有之規劃提供，對於特定使用者之特殊需求，「666娛樂城」不擔保本服務將符合&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;您的所有需求。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（二）「666娛樂城」不擔保各項服務之正確、完整、安全、可靠、合適、時效、穩定、不會斷線及出錯。您同意對於您所傳送之電子郵件、檔案&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;及其他資料做備份。關於因傳送過程而造成電子郵件、檔案及其他相關電磁記錄資料之遺失，「666娛樂城」不負任何擔保責任。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（三）對於您於本服務中所下載之電子郵件、檔案及其他資料，您應該自行考量其風險，如因下載而造成您電腦系統的損壞或電腦中資料的遺&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;失，「666娛樂城」不負任何擔保責任。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（四）「666娛樂城」服務可能因自身、其他協力廠商或相關電信業者網路系統軟硬體設備之故障或失靈；或人為操作上之疏失而造成中斷、暫時&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;無法使用、遲延、資料傳輸或儲存上之錯誤；或遭第三人侵入系統篡改或偽造變造資料等，「666娛樂城」就以上情形不保證各項服務之穩&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;定、安全、無誤、及不中斷，僅於能力範圍內提供合理之維護修復。會員需明白使用本服務之所有風險及可能致生之任何損害，不得因此&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;而要求任何補償或賠償。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第九條】 保管義務&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;會員有義務妥善保管在「666娛樂城」之帳號與密碼，並為此組帳號與密碼登入系統後所進行之一切活動負責。為維護會員自身權益，請勿將帳號與密碼洩露或提供予第三人知悉，或出借或轉讓他人使用。若會員發現帳號或密碼遭人非法使用或有任何異常破壞使用安全之情形時，應立即通知「666娛樂城」。但若是因為您的保管疏忽，而導致帳號、密碼遭他人非法使用時，「666娛樂城」將不負責處理。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第十條】 資料處理&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;對於會員所登錄或留存之個人資料，會員同意「666娛樂城」及關係企業或合作對象，得於合理之範圍內（非營利目的）蒐集、處理、保存、傳遞及使用該等資料，以提供會員其他資訊或服務；或作成會員統計資料、進行關於網路行為之調查或研究或為任何之合法使用。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第十一條】 隱私權保護&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（一）司法或警察機關偵查犯罪需要時。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（二）政府機關依法律程序要求時。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（三）因會員之行為違反法令或本服務條款之規定時。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;（四）於維護公益或保護收數王或他人權利。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第十二條】 資料處理&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;「666娛樂城」得於一個月前在網頁上公告後，即取消、停止本服務之全部或一部，會員不得因此要求補償或賠償。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;【第十三條】 資料處理&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.38;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:#ff99ff;&quot;&gt;&lt;span id=&quot;docs-internal-guid-72c0eeac-582e-157b-57e9-cf366fde062b&quot;&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;&amp;nbsp;&amp;nbsp; &amp;nbsp;&lt;/span&gt;&lt;span style=&quot;font-size: 10pt; font-family: Arial; background-color: transparent; vertical-align: baseline; white-space: pre-wrap;&quot;&gt;本服務保留將來新增、修改或刪除本服務之全部或一部之權利，且不另行個別通知，會員不得因此而要求任何補償或賠償。&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;div&gt;&lt;/div&gt;
</textarea>
                            </div>
                          </div>
                          <div class="form-group">
                            <div class="col-xs-12 col-sm-12 center">
                              <button type="submit" class="btn btn-primary">送出</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
              <!-- 主要内容 结束 -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div>
        <!-- /.page-content -->
      </div>
    </div><!-- /.main-content -->
    <?php include "include/in_footer.php"?>
  </div><!-- /.main-container -->
  <div id="sound"></div>
  <!-- ace scripts -->
  <script src="js/ace-elements.min.js"></script>
  <script src="js/ace.min.js"></script>
</body>

</html>
